import assert from 'node:assert/strict';
import { parseLaunch, claimLaunch, cancelLaunch, LAUNCH_TTL_MS } from '../ninja/launch.js';
const token = 'a'.repeat(32), now = 1000;
const pending = { game: 'ninja', status: 'waiting-screen', createdAt: now, launch: { token, expiresAt: now + LAUNCH_TTL_MS } };
assert.deepEqual(parseLaunch('#launch=123456.' + token), { code: '123456', token });
for (const hash of ['', '#launch=12345.' + token, '#launch=123456.bad', '#launch=123456.' + token + '&extra=1']) assert.equal(parseLaunch(hash), null);
assert.equal(claimLaunch(pending, 'b'.repeat(32), now), undefined);
assert.equal(claimLaunch(pending, token, pending.launch.expiresAt), undefined);
assert.equal(claimLaunch({ ...pending, game: 'another-game' }, token, now), undefined);
const claimed = claimLaunch(pending, token, now);
assert.equal(claimed.status, 'lobby');
assert.equal(claimed.launch.claimed, true);
assert.equal(claimLaunch(claimed, token, now), undefined, 'one screen only');
assert.equal(cancelLaunch(claimed, token), undefined, 'app cleanup cannot delete a claimed game');
assert.equal(cancelLaunch(pending, 'wrong'), undefined);
assert.equal(cancelLaunch({ ...pending, game: 'another-game' }, token), undefined);
assert.equal(cancelLaunch(pending, token), null);
assert.equal(pending.status, 'waiting-screen', 'callbacks do not mutate transaction input');
console.log('LAUNCH TEST: PASS - parsing, expiry, ownership, single screen and cancellation races');
